### ISSUE TITLE
Device and partition resolution does not work for NVMe based storage

### ISSUE THREAD

**Issue by ygalblum** [ygalblum/ansible-bash-bigboot#5]
The current implementation assumes that the partition's path is always: `/dev/<Device><Counter>`, e.g. for device `/dev/vda` the partitions are `/dev/vda1`, `/dev/vda2` etc.

However, when in some cases, e.g. NVMe, this is not the case and an additional letter is used. So, for partition of disk `/dev/nvme0n1` is `/dev/nvme0n1p1`.

This root cause has several effects on the code.
In the Ansible role, should use:
```
- name: Identify the boot device parent
  ansible.builtin.command: "lsblk -spnlo name {{ _boot_device.device }}"
  changed_when: false
  register: _boot_device_deps

- name: Capture boot device details
  ansible.builtin.set_fact:
    boot_device_name: "{{ _boot_device_deps.stdout_lines | last }}"
    boot_device_original_size: "{{ _boot_device.size_total | int }}"
```

In the `shrink.sh` script 
```
ensure_extendable_fs_type "$DEVICE_NAME""$BOOT_PARTITION_NUMBER"
```

In addition the `BOOT_PARTITION_FLAG` is not always set:
```
[root@steady-midge ~]# parted -m /dev/nvme0n1 print
BYT;
/dev/nvme0n1:32.2GB:nvme:512:512:msdos:NVMe Device:;
1:1049kB:500MB:499MB:ext4::;
2:500MB:32.2GB:31.7GB:::lvm;
```
Consider finding the boot partition based on fstab
